openapi: 3.0.3
info:
  title: Devstream Aurelia OpenAPI Specification
  version: 0.3.42
  description: API reference for Devstream platform built with Spring Boot.
  termsOfService: https://www.devstream.in/terms-and-conditions
  license:
    name: GPL-2.0-only
    url: https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html#SEC1
tags:
  - name: Auth
    description: Endpoints related to user authentication (login, register, refresh
      token, forgot password, reset password).
  - name: Content
    description: Endpoints for managing content (creating, retrieving, updating,
      deleting content, analytics).
  - name: Health
    description: Endpoint for checking the health of the API service.
  - name: Platforms
    description: Endpoints for interacting with external platforms (syncing data,
      retrieving platform information).
  - name: User
    description: Endpoints for managing user information (profile, settings, analytics).
  - name: Pipeline
    description: Endpoints to deal with user content publishing pipeline.
servers:
  - url: "{protocol}://{environment}.devstream.in/v1"
    variables:
      protocol:
        default: https
        enum:
          - http
          - https
      environment:
        default: api
        enum:
          - api
          - api.dev
          - api.staging
          - api.test
paths:
  /health:
    $ref: ./src/paths/health.yml
  /user/profile:
    $ref: ./src/paths/user_profile.yml
  /user/settings:
    $ref: ./src/paths/user_settings.yml
  /user/analytics:
    $ref: ./src/paths/user_analytics.yml
  /user/deactivate:
    $ref: ./src/paths/user_deactivate.yml
  /user/content:
    $ref: ./src/paths/user_content.yml
  /user/password:
    $ref: ./src/paths/user_password.yml
  /auth/login:
    $ref: ./src/paths/auth_login.yml
  /auth/two-factor-auth:
    $ref: ./src/paths/auth_two-factor-auth.yml
  /auth/register:
    $ref: ./src/paths/auth_register.yml
  /auth/token:
    $ref: ./src/paths/auth_token.yml
  /recovery/initiate:
    $ref: ./src/paths/recovery_initiate.yml
  /recovery/token:
    $ref: ./src/paths/recovery_token.yml
  /recovery/reset:
    $ref: ./src/paths/recovery_reset.yml
  /content/{ContentID}:
    $ref: ./src/paths/content_{id}.yml
  /content/status/{ContentID}:
    $ref: ./src/paths/content_status_{id}.yml
  /content/collaboration/{ContentID}:
    $ref: ./src/paths/content_collaboration_{id}.yml
  /content/analytics/{ContentID}:
    $ref: ./src/paths/content_analytics_{id}.yml
  /content/upload-finish/{ContentID}:
    $ref: ./src/paths/content_upload-finish_{id}.yml
  /platforms/{PlatformID}:
    $ref: ./src/paths/platforms_{id}.yml
  /platforms/sync:
    $ref: ./src/paths/platforms_sync.yml
  /pipeline:
    $ref: ./src/paths/pipeline.yml
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
