get:
  summary: Gets all the pipelines created by the user as well as predefined
    pipelines.
  description: Get pipelines saved for a particular user. Todo is to decide whether
    prebuild pipelines are also send alongside user pipelines in this.
  operationId: get-pipelines
  tags:
    - Pipeline
  security:
    - BearerAuth: []
  responses:
    200:
      description: All pipelines defined by a particular user as well as predefined
        common pipelines.
      content:
        application/json:
          schema:
            $ref: ../dto/ResponseGetPipeline.yml
    # TODO: Add a 400 Bad Request response.
    404:
      description: No predefined or saved pipeline found.

post:
  summary: Creates a new user specification for content processing pipeline.
  operationId: create-pipeline
  tags:
    - Pipeline
  security:
    - BearerAuth: []
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../dto/RequestCreatePipeline.yml
  responses:
    201:
      description: Pipeline specification created successfully.
      content:
        application/json:
          schema:
            $ref: ../dto/ResponseCreatePipeline.yml
    400:
      description: Bad Request, invalid inputs.

patch:
  summary: Modify a new user specification for content processing pipeline.
  operationId: modify-pipeline
  tags:
    - Pipeline
  security:
    - BearerAuth: []
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../dto/RequestUpdatePipeline.yml
  responses:
    204:
      description: Pipeline specification modified successfully.
    400:
      description: Bad Request, invalid inputs.
    401:
      description: Unauthorized. Authentication required to update pipeline.
    404:
      description: Not found. The pipeline does not exist.
