get:
  summary: Gets all the pipelines created by the user as well as predefined
    pipelines.
  description: Get pipelines saved for a particular user. Todo is to decide whether
    prebuild pipelines are also send alongside user pipelines in this.
  operationId: get-pipelines-for-user
  tags:
    - Pipeline
  security:
    - BearerAuth: []
  responses:
    200:
      description: All pipelines defined by a particular user as well as predefined
        common pipelines.
      content:
        application/json:
          schema:
            $ref: ../dto/ResponseGetPipeline.yml
    # TODO: Add a 400 Bad Request response.
    400:    # TODO: Should this be 404?
      description: No predefined or saved pipeline found.

post:
  summary: Creates a new user specification for content processing pipeline.
  operationId: create-pipeline-specification
  tags:
    - Pipeline
  security:
    - BearerAuth: []
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../dto/RequestCreatePipeline.yml
  responses:
    200:
      description: Pipeline specification created successfully.
      content:
        application/json:
          schema:
            $ref: ../dto/ResponseCreatePipeline.yml
    400:
      description: Bad Request, invalid inputs.
