get:
  summary: Retrieve user-specific settings.
  operationId: get-user-settings
  tags:
    - User
  security:
    - BearerAuth: []
  responses:
    200:
      description: Settings retrieved successfully.
      content:
        application/json:
          schema:
            $ref: "../components/responses/GetUserSettingsResponse.yml"
    401:
      description: Unauthorized. Authentication required to view settings.

patch:
  summary: Update user-specific settings.
  operationId: update-user-settings
  tags:
    - User
  security:
    - BearerAuth: []
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../components/requestBodies/UpdateUserSettingsRequest.yml"
  responses:
    200:
      description: Settings updated successfully.
    400:
      description: Bad request. Invalid request format or missing required fields.
    401:
      description: Unauthorized. Authentication required to update settings.
