name: Compile OpenAPI Specification
description: Sets up OpenAPI by caching dependencies and running initial commands.

inputs:
  node-version:
    description: Node.js version
    default: "22.x"
  java-version:
    description: Java version
    default: "21"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Hash Dependencies
      shell: bash
      run: echo "ROOT_DEPS_HASH=$(node ./scripts/hash-node-deps.js ./package.json)" >> "$GITHUB_ENV"

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: "https://npm.pkg.github.com"
        scope: "@adityamayukhsom"

    - name: Cache Java Installation
      uses: actions/cache@v3
      with:
        path: |
          C:\hostedtoolcache\windows\Java_Corretto_jdk
          C:\Users\runneradmin\.m2
        key: java-corretto-${{ inputs.java-version }}

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: "corretto"
        java-version: ${{ inputs.java-version }}

    - name: Get NPM cache path
      shell: bash
      id: set-npm-cache-path
      run: echo "NPM_CACHE_PATH=$(npm config get cache)" >> "$GITHUB_ENV"

    - name: Cache Node.js Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.NPM_CACHE_PATH }}
          ./node_modules
        key: ${{ runner.os }}-node-${{ env.ROOT_DEPS_HASH }}

    - name: Install Dependencies
      shell: pwsh
      run: npm install --omit=optional --omit=dev --ignore-scripts

    - name: Bundle OpenAPI Specification
      shell: pwsh
      run: npm run openapi:mint
