name: build openapi specification
description: bundles up up openapi by setting up node and java environments,
  caching dependencies and running commands. also sets caches in the process
  for faster successive build.

inputs:
  node-version:
    description: Node.js version
    default: "22.x"
  java-version:
    description: Java version
    default: "21"

runs:
  using: "composite"
  steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: save openapi generator dependency hash and npm cache path as environment variable
      shell: bash
      run: |
        echo "ROOT_DEPS_HASH=$(node ./scripts/hash-node-deps.js ./package.json)" >> "$GITHUB_ENV"
        echo "NPM_CACHE_PATH=$(npm config get cache)" >> "$GITHUB_ENV"

    - name: cache java executable and node modules
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.NPM_CACHE_PATH }}
          ./node_modules
          C:\hostedtoolcache\windows\Java_Corretto_jdk
          C:\Users\runneradmin\.m2
        key: ${{ runner.os }}-node-${{ env.ROOT_DEPS_HASH }}-java-corretto-${{ inputs.java-version }}

    - name: setup nodejs
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: "https://npm.pkg.github.com"
        scope: "@adityamayukhsom"

    - name: setup jdk and jre
      uses: actions/setup-java@v4
      with:
        distribution: "corretto"
        java-version: ${{ inputs.java-version }}

    - name: install npm dependencies (not ci, so to use node_modules from cache)
      shell: pwsh
      run: npm install --ignore-scripts

    - name: bundle openapi specification
      shell: pwsh
      run: npm run openapi:mint
